language: c
 
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_bioc Biostrings
  - ./travis-tool.sh install_bioc EBImage
  - ./travis-tool.sh install_bioc EBImage
  - ./travis-tool.sh install_r ape
  - ./travis-tool.sh install_r plyr
  - ./travis-tool.sh install_r dplyr
  - ./travis-tool.sh install_r sp
  - ./travis-tool.sh install_r reshape2
  - ./travis-tool.sh install_r ggplot2
  - ./travis-tool.sh install_r geometry
  - ./travis-tool.sh install_r jpeg
  - ./travis-tool.sh install_r MASS
  - ./travis-tool.sh install_r knitr
  - ./travis-tool.sh install_github GuangchuangYu/ggtree
  - ./travis-tool.sh install_bioc_deps


on_failure:
  - ./travis-tool.sh dump_logs

after_script:
  - ./travis-tool.sh dump_logs_by_extension "timings"
  - ./travis-tool.sh dump_sysinfo

notifications:
  email:
    on_success: change
    on_failure: change
