language: r

sudo: required

apt_packages:
 - libfftw3-dev
 
bioc_required: true

r_binary_packages:
  - ape
  - plyr
  - dplyr
  - sp
  - reshape2
  - ggplot2
  - geometry
  - graphics
  - jpeg
  - MASS
  - utils
  - knitr

bioc_packages:
 - Biostrings
 - EBImage
 - BiocStyle
 
r_github_packages:
 - GuangchuangYu/ggtree
 
notifications:
  email:
    on_success: change
    on_failure: change

